platform:
  name: "@hkyhy/marsun-components-core"
  code_prefix: CC-0.1

repo_root: .

milestones:
  data: plane/milestones.yaml

projects_tasks:
  projects: plane/projects.yaml
  tasks: plane/tasks.yaml
