import type { Dataset, KBDocument } from '@/components/AgentHub/types';

export const mockDatasets: Dataset[] = [
  {
    id: 'kb-1',
    name: '企业制度手册',
    description: '包含考勤、休假、报销等制度文档',
    chunk_count: 1280,
    document_count: 24,
    token_num: 520000,
    embedding_model: 'BAAI/bge-m3',
    done_count: 22,
    running_count: 1,
    fail_count: 1,
    unstart_count: 0,
  },
  {
    id: 'kb-2',
    name: '产品技术文档',
    description: 'API 文档与架构设计说明',
    chunk_count: 860,
    document_count: 12,
    token_num: 310000,
    embedding_model: 'BAAI/bge-large-zh-v1.5',
    done_count: 12,
    running_count: 0,
    fail_count: 0,
    unstart_count: 0,
  },
  {
    id: 'kb-3',
    name: '客户服务 FAQ',
    description: '常见问题与标准回复话术，正在初始化',
    chunk_count: 0,
    document_count: 5,
    token_num: 0,
    embedding_model: 'text-embedding-3-small',
    done_count: 0,
    running_count: 2,
    fail_count: 0,
    unstart_count: 3,
  },
];

export const mockDocuments: KBDocument[] = [
  {
    id: 'doc-1',
    name: '员工休假管理制度.pdf',
    dataset_id: 'kb-1',
    type: 'pdf',
    size: 1024 * 512,
    run: 'DONE',
    chunk_count: 48,
    create_time: '2026-05-10',
  },
  {
    id: 'doc-2',
    name: '考勤管理办法.pdf',
    dataset_id: 'kb-1',
    type: 'pdf',
    size: 1024 * 256,
    run: 'RUNNING',
    chunk_count: 0,
    create_time: '2026-06-01',
  },
  {
    id: 'doc-3',
    name: '报销流程说明.docx',
    dataset_id: 'kb-1',
    type: 'docx',
    size: 1024 * 128,
    run: 'FAIL',
    chunk_count: 0,
    create_time: '2026-06-05',
  },
  {
    id: 'doc-4',
    name: '新员工入职指南.pdf',
    dataset_id: 'kb-1',
    type: 'pdf',
    size: 1024 * 768,
    run: 'UNSTART',
    chunk_count: 0,
    create_time: '2026-06-08',
  },
];
